# Load Numpy and check version

In [2]:
import numpy as np
np.__version__

'1.21.5'

# creat an 1D array using array function

In [3]:
import numpy as np
a = np.array([2,3,4,5,6])
print(a)
print(a.dtype)
print(a.shape)

[2 3 4 5 6]
int32
(5,)


# create a 1D array using arange function

In [4]:
import numpy as np
a = np.arange(5)
print(a)
print(a.dtype)
print(a.shape)

[0 1 2 3 4]
int32
(5,)


# create 2D array using array function

In [6]:
import numpy as np
a = np.array([[2,3,4,5,6],[5,6,7,8,9]])
print(a)
print(a.dtype)
print(a.shape)

[[2 3 4 5 6]
 [5 6 7 8 9]]
int32
(2, 5)


# create 2D array using arange function

In [8]:
import numpy as np
a = np.arange(9).reshape(3,3)
print(a)
print(a.dtype)
print(a.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
int32
(3, 3)


# create 3D array using array fuction

In [3]:
import numpy as np
a = np.array([[[2,3],[5,6]],[[5,6],[7,8]],[[2,3],[5,6]]])
print(a)
print(a.dtype)
print(a.shape)

[[[2 3]
  [5 6]]

 [[5 6]
  [7 8]]

 [[2 3]
  [5 6]]]
int32
(3, 2, 2)


# create an 3D array using arange fuction

In [5]:
import numpy as np
a = np.arange(12).reshape(3,2,2)
print(a)
print(a.dtype)
print(a.shape)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
int32
(3, 2, 2)


# creating array of ones 

In [9]:
import numpy as np
a = np.ones(12,dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[1 1 1 1 1 1 1 1 1 1 1 1]
int32
(12,)


In [10]:
import numpy as np
a = np.ones((2,3),dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[[1 1 1]
 [1 1 1]]
int32
(2, 3)


# create an array with random numbers D

In [16]:
import numpy as np
a = np.random.randint(2,3,size=5)
print(a)
print(a.dtype)
print(a.shape)

[2 2 2 2 2]
int32
(5,)


In [20]:
import numpy as np
a = np.random.randint(5,10,size=(2,3))
print(a)

[[9 6 7]
 [9 9 5]]


In [21]:
import numpy as np
a = np.random.randint(5,10,size=(3,3,3))
print(a)

[[[9 9 8]
  [8 5 9]
  [5 5 5]]

 [[9 8 9]
  [9 6 7]
  [8 5 6]]

 [[9 6 8]
  [7 5 8]
  [7 9 9]]]


# creating random numbers with upper bond

In [25]:
import numpy as np
a = np.random.randint(5,[10,20,30])
print(a)

[ 7 17 25]


In [27]:
import numpy as np
a = np.random.randint([5,8,6],20,size=(2,3))
print(a)

[[10 13  7]
 [11 12 14]]


In [31]:
import numpy as np
a = np.random.randint((5,6,7),(10,20,30),size=(2,3))
print(a)

[[ 8 10 14]
 [ 9 15 10]]


# random randn and rand function

In [4]:
import numpy as np
a = np.random.randn(3)
print(a)
print(a.dtype)
print(a.shape)

[-0.0478104   0.53468727  1.19196808]
float64
(3,)


In [5]:
import numpy as np
a = np.random.randn(2,5)
print(a)
print(a.dtype)
print(a.shape)

[[ 0.47977288  0.73739891 -1.02319045 -1.36968637  1.39101844]
 [ 1.59074903  1.19137308  0.05806618 -0.11608335 -0.1014277 ]]
float64
(2, 5)


In [11]:
import numpy as np
a = np.random.rand(2,5)
print(a)
print(a.dtype)
print(a.shape)

[[0.70627899 0.98714931 0.16907242 0.60815548 0.94225248]
 [0.19261677 0.26581659 0.23984683 0.55328013 0.025551  ]]
float64
(2, 5)


# array indexing

In [15]:
import numpy as np
a = np.array([2,3,4,5])
print(a[2])

4


In [17]:
import numpy as np
a = np.array([[2,3,4,5],[9,8,6,7]])
print(a[1,2])

6


In [19]:
import numpy as np
a = np.array([[[2,3],[4,5]],[[6,7],[8,9]]])
print(a[1,0,1])

7


In [20]:
import numpy as np
a = np.array([[[2,3],[4,5]],[[6,7],[8,9]]])
print(a[-1,0,-1])

7


In [21]:
import numpy as np
a = np.array([[[2,3],[4,5]],[[6,7],[8,9]]])
print(a[-2,-1,-2])

4


# array numpy slicing

In [4]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a[1:5])

[2 3 4 5]


In [5]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
print(a[4:])

[5 6 7]


In [6]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
print(a[:4])

[1 2 3 4]


# negative slicing

In [8]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
print(a[-3:-1])

[5 6]


In [10]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
print(a[1:5:2])

[2 4]


In [13]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
print(a[::2])

[1 3 5 7]


# slicing 2-D Array

In [15]:
import numpy as np
a = np.array([[1,2,3,4,5,9],[5,6,7,8,9,0]])
print(a[1,1:4])

[6 7 8]


In [19]:
import numpy as np
a = np.array([[1,2,3,4,5,9],[5,6,7,8,9,0]])
print(a[0:2,2])

[3 7]


In [21]:
import numpy as np
a = np.array([[1,2,3,4,5,9],[5,6,7,8,9,0]])
print(a[0:,1:4])

[[2 3 4]
 [6 7 8]]


# numpay array copy vs view

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy. The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

# copy

In [1]:
import numpy as np
arr=np.array([1,3,5,7,9])
x=arr.copy()
arr[2]=11
print(arr)
x[1]=4
print(x)

[ 1  3 11  7  9]
[1 4 5 7 9]


In [2]:
import numpy as np
arr=np.array([1,3,5,7,9])
x=arr.view()
arr[2]=11
print(arr)
print(x)

[ 1  3 11  7  9]
[ 1  3 11  7  9]


# reshaping

Reshaping means changing the shape of an array. The shape of an array is the number of elements in each dimension. By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [3]:
import numpy as np
arr=np.array([1,3,5,7])
print(arr)
x=arr.reshape(2,2)
print(x)

[1 3 5 7]
[[1 3]
 [5 7]]


In [4]:
import numpy as np
arr=np.array([1,3,5,7,9,11,13,15,17,19,21,23])
x=arr.reshape(2,3,2)
print(x)

[[[ 1  3]
  [ 5  7]
  [ 9 11]]

 [[13 15]
  [17 19]
  [21 23]]]


In [5]:
import numpy as np
arr=np.array([1,3,5,7,9,11,13,15,17,19,21,23])
x=arr.reshape(3,2,2)
print(x)

[[[ 1  3]
  [ 5  7]]

 [[ 9 11]
  [13 15]]

 [[17 19]
  [21 23]]]


# sum

In [7]:
#np.sum(array_name): Returns the sum of array elements (all row and columns).
import numpy as np
a=np.array([2,4,6,8])
print(np.sum(a))

20


In [8]:
import numpy as np 
a=np.array([[2,4,6,8],[1,3,5,7]] )
print(np.sum(a))

36


In [9]:
#np.sum(array_name, axis=0 or 1): Returns the sum of array elements over a given axis.
import numpy as np 
a=np.array([[2,4,6,8],[1,3,5,7]] )
print(np.sum(a))
print(" accross rows")
print(np.sum(a, axis=0))
print("accross columns")
print(np.sum(a, axis=1))

36
 accross rows
[ 3  7 11 15]
accross columns
[20 16]


In [10]:
import numpy as np
a=np.array([[[1,2,3,4],[2,3,4,5],[3,4,5,6]]])
print(np.sum(a))
print(" accross rows")
print(np.sum(a, axis=0))
print("accross columns")
print(np.sum(a, axis=1))

42
 accross rows
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
accross columns
[[ 6  9 12 15]]


# mean

In [11]:
#np.mean(array_name): Computes the arithmetic mean of given array (all row and columns).
import numpy as np
a=np.array([2,4,6,8])
print(a)
print(np.mean(a))

[2 4 6 8]
5.0


In [12]:
import numpy as np
a=np.array([[2,4,6,8],[1,3,5,7]])
print(a)
print(np.mean(a))

[[2 4 6 8]
 [1 3 5 7]]
4.5


In [13]:
#np.mean(array_name, axis=0 or 1): Returns the arithmetic mean of given array elements over a given axis.

import numpy as np 
a=np.array([[2,4,6,8],[1,3,5,7]] )
print(a)
print("\n accross rows" ,np.mean(a, axis=0))
print("\n accross cloumns" ,np.mean(a, axis=1))

[[2 4 6 8]
 [1 3 5 7]]

 accross rows [1.5 3.5 5.5 7.5]

 accross cloumns [5. 4.]


# standard deviation

In [14]:
#np.std(array_name): Computes the standard deviation along the specified axis. (all row and columns).

import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(np.std(arr))


[1 2 3 4]
1.118033988749895


In [15]:
#np.std(array_name, axis= 0 or 1): Computes the standard deviation along the specified axis.
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(np.std(arr))
print("accross rows")
print(np.std(arr, axis=0))
print("accross columns")
print(np.std(arr, axis=1))

[[1 2 3 4]
 [5 6 7 8]]
2.29128784747792
accross rows
[2. 2. 2. 2.]
accross columns
[1.11803399 1.11803399]


# variance

In [16]:
#np.var(array_name): Computes the variance along the specified axis. (all row and columns).
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(np.var(arr))

[1 2 3 4]
1.25


In [17]:
#np.var(array_name, axis= 0 or 1): Computes the variance along the specified axis.
import numpy as np
arr=np.array([[1,2,3,4],[2,4,6,8]])
print("\n",arr)
print("\n",np.var(arr))
print("\n",np.var(arr, axis=0))
print("\n",np.var(arr, axis=1))


 [[1 2 3 4]
 [2 4 6 8]]

 4.6875

 [0.25 1.   2.25 4.  ]

 [1.25 5.  ]


# minimum

In [18]:
#np.min(array_name): Returns the indices of the minimum values along an axis.. (all row and columns).
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr)
print(np.min(arr))

[1 2 3 4 5 6 7]
1


In [19]:
import numpy as np
arr=np.array([[1,2,3,4],[11,12,13,14]])
print(arr)
print(np.min(arr))

[[ 1  2  3  4]
 [11 12 13 14]]
1


In [20]:
#np.min(array_name, axis= 0 or 1): Returns the indices of the minimum values along an axis...
import numpy as np
arr=np.array([[1,2,3,4],[11,12,13,14]])
print("\n",arr)
print("\n",np.min(arr))
print("\n",np.min(arr, axis=0))
print("\n",np.min(arr, axis=1))


 [[ 1  2  3  4]
 [11 12 13 14]]

 1

 [1 2 3 4]

 [ 1 11]


# maximum

In [21]:
#np.max(array_name): Returns the indices of the max values along an axis.. (all row and columns).
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr)
print(np.max(arr))

[1 2 3 4 5 6 7]
7


In [22]:
import numpy as np
arr=np.array([[1,2,3,4],[11,12,13,14]])
print(arr)
print(np.max(arr))

[[ 1  2  3  4]
 [11 12 13 14]]
14


In [23]:
#np.max(array_name, axis= 0 or 1): Returns the indices of the maximum values along an axis...
import numpy as np
arr=np.array([[1,2,3,4],[11,12,13,14]])
print("\n original",arr)
print("\n maximum",np.max(arr))
print("\n maximum accross rows",np.max(arr, axis=0))
print("\n maximum accross columns",np.max(arr, axis=1))


 original [[ 1  2  3  4]
 [11 12 13 14]]

 maximum 14

 maximum accross rows [11 12 13 14]

 maximum accross columns [ 4 14]
