In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [41]:
df = pd.read_csv("dataset/cgpa_marks_package.csv")
df

cgpa  Interview_marks  package
0    6.89               26     3.26
1    5.12               38     1.98
2    7.82               40     3.25
3    7.42                8     3.67
4    6.94               17     3.57
..    ...              ...      ...
195  6.93               44     2.46
196  5.89               34     2.57
197  7.21               27     3.24
198  7.63               44     3.96
199  6.22               25     2.33

[200 rows x 3 columns]

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   cgpa             200 non-null    float64
 1   Interview_marks  200 non-null    int64  
 2   package          200 non-null    float64
dtypes: float64(2), int64(1)
memory usage: 4.8 KB


In [43]:
x=df[['cgpa','Interview_marks']]
x

cgpa  Interview_marks
0    6.89               26
1    5.12               38
2    7.82               40
3    7.42                8
4    6.94               17
..    ...              ...
195  6.93               44
196  5.89               34
197  7.21               27
198  7.63               44
199  6.22               25

[200 rows x 2 columns]

In [44]:
y=df[['package']]
y

package
0       3.26
1       1.98
2       3.25
3       3.67
4       3.57
..       ...
195     2.46
196     2.57
197     3.24
198     3.96
199     2.33

[200 rows x 1 columns]

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=2)

In [47]:
x_train.shape

(160, 2)

In [48]:
y_train

package
137     3.13
163     3.91
111     2.25
123     2.30
109     4.06
..       ...
43      2.76
22      2.30
72      3.62
15      3.23
168     3.52

[160 rows x 1 columns]

In [49]:
x_test

cgpa  Interview_marks
112  8.58               15
29   7.15               15
182  5.88               76
199  6.22               25
193  4.57               14
85   4.79               28
10   5.32               16
54   6.86               36
115  8.35               37
35   6.87               12
12   8.94               16
92   7.90               63
13   6.93               26
126  5.91               37
174  7.32               21
2    7.82               40
44   5.09               55
3    7.42                8
113  6.94               10
14   7.73               43
23   6.19               11
25   7.28               58
6    6.73               11
134  7.20               93
165  8.21                7
173  6.75               48
45   7.87               10
65   7.60               28
48   8.63               42
122  5.12               51
178  8.15               39
64   7.36               52
9    8.31               94
57   6.60               24
78   6.59               12
71   7.47               20
128  7.93               25
176  6.29               30
131  6.37               19
53   6.47               33

In [50]:
from sklearn.linear_model import LinearRegression

In [51]:
lr=LinearRegression()

In [52]:
lr.fit(x_train,y_train)

LinearRegression()

In [53]:
A=lr.predict(x_test)

In [54]:
A

array([[3.89979454],
       [3.10237603],
       [2.36034882],
       [2.57822923],
       [1.66423151],
       [1.77914693],
       [2.08134881],
       [2.92901527],
       [3.7593373 ],
       [2.94790193],
       [4.09998866],
       [3.49398191],
       [2.97359571],
       [2.39870713],
       [3.19384646],
       [3.4621268 ],
       [1.93146344],
       [3.25681974],
       [2.9880456 ],
       [3.41027583],
       [2.56926451],
       [3.151021  ],
       [2.87038758],
       [3.08699931],
       [3.69790624],
       [2.86102024],
       [3.50664644],
       [3.34610218],
       [3.91270221],
       [1.95041088],
       [3.64670105],
       [3.1989594 ],
       [3.70541992],
       [2.79068524],
       [2.79176404],
       [3.27804635],
       [3.53178562],
       [2.61449072],
       [2.6652021 ],
       [2.71320129]])

In [55]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,A)

0.2873891848877421

In [56]:
from sklearn.metrics import r2_score
r2_score(y_test,A)

0.7805012233012033

In [57]:
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,A)
mse

0.12141898593789571

In [58]:
np.sqrt(mse)

0.34845227210895857

In [59]:
lr.coef_

array([[ 5.57635318e-01, -5.54595982e-04]])

In [63]:
lr.intercept_

array([-0.87639755])