In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [35]:
df = pd.read_csv('dataset/bank-additional-full.csv')
df

age          job  marital            education  default housing loan  \
0       56    housemaid  married             basic.4y       no      no   no   
1       57     services  married          high.school  unknown      no   no   
2       37     services  married          high.school       no     yes   no   
3       40       admin.  married             basic.6y       no      no   no   
4       56     services  married          high.school       no      no  yes   
...    ...          ...      ...                  ...      ...     ...  ...   
41183   73      retired  married  professional.course       no     yes   no   
41184   46  blue-collar  married  professional.course       no      no   no   
41185   56      retired  married    university.degree       no     yes   no   
41186   44   technician  married  professional.course       no      no   no   
41187   74      retired  married  professional.course       no     yes   no   

         contact month day_of_week  ...  campaign  pdays  previous  \
0      telephone   may         mon  ...         1    999         0   
1      telephone   may         mon  ...         1    999         0   
2      telephone   may         mon  ...         1    999         0   
3      telephone   may         mon  ...         1    999         0   
4      telephone   may         mon  ...         1    999         0   
...          ...   ...         ...  ...       ...    ...       ...   
41183   cellular   nov         fri  ...         1    999         0   
41184   cellular   nov         fri  ...         1    999         0   
41185   cellular   nov         fri  ...         2    999         0   
41186   cellular   nov         fri  ...         1    999         0   
41187   cellular   nov         fri  ...         3    999         1   

          poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
0      nonexistent          1.1          93.994          -36.4      4.857   
1      nonexistent          1.1          93.994          -36.4      4.857   
2      nonexistent          1.1          93.994          -36.4      4.857   
3      nonexistent          1.1          93.994          -36.4      4.857   
4      nonexistent          1.1          93.994          -36.4      4.857   
...            ...          ...             ...            ...        ...   
41183  nonexistent         -1.1          94.767          -50.8      1.028   
41184  nonexistent         -1.1          94.767          -50.8      1.028   
41185  nonexistent         -1.1          94.767          -50.8      1.028   
41186  nonexistent         -1.1          94.767          -50.8      1.028   
41187      failure         -1.1          94.767          -50.8      1.028   

       nr.employed    y  
0           5191.0   no  
1           5191.0   no  
2           5191.0   no  
3           5191.0   no  
4           5191.0   no  
...            ...  ...  
41183       4963.6  yes  
41184       4963.6   no  
41185       4963.6   no  
41186       4963.6  yes  
41187       4963.6   no  

[41188 rows x 21 columns]

In [36]:
df.shape

(41188, 21)

In [37]:
df.describe()

age      duration      campaign         pdays      previous  \
count  41188.00000  41188.000000  41188.000000  41188.000000  41188.000000   
mean      40.02406    258.285010      2.567593    962.475454      0.172963   
std       10.42125    259.279249      2.770014    186.910907      0.494901   
min       17.00000      0.000000      1.000000      0.000000      0.000000   
25%       32.00000    102.000000      1.000000    999.000000      0.000000   
50%       38.00000    180.000000      2.000000    999.000000      0.000000   
75%       47.00000    319.000000      3.000000    999.000000      0.000000   
max       98.00000   4918.000000     56.000000    999.000000      7.000000   

       emp.var.rate  cons.price.idx  cons.conf.idx     euribor3m   nr.employed  
count  41188.000000    41188.000000   41188.000000  41188.000000  41188.000000  
mean       0.081886       93.575664     -40.502600      3.621291   5167.035911  
std        1.570960        0.578840       4.628198      1.734447     72.251528  
min       -3.400000       92.201000     -50.800000      0.634000   4963.600000  
25%       -1.800000       93.075000     -42.700000      1.344000   5099.100000  
50%        1.100000       93.749000     -41.800000      4.857000   5191.000000  
75%        1.400000       93.994000     -36.400000      4.961000   5228.100000  
max        1.400000       94.767000     -26.900000      5.045000   5228.100000

In [38]:
df.drop('duration',axis=1,inplace=True)

In [39]:
y=df[['y']]
y

y
0       no
1       no
2       no
3       no
4       no
...    ...
41183  yes
41184   no
41185   no
41186  yes
41187   no

[41188 rows x 1 columns]

In [40]:
x=df.iloc[:,:-1]
x

age          job  marital            education  default housing loan  \
0       56    housemaid  married             basic.4y       no      no   no   
1       57     services  married          high.school  unknown      no   no   
2       37     services  married          high.school       no     yes   no   
3       40       admin.  married             basic.6y       no      no   no   
4       56     services  married          high.school       no      no  yes   
...    ...          ...      ...                  ...      ...     ...  ...   
41183   73      retired  married  professional.course       no     yes   no   
41184   46  blue-collar  married  professional.course       no      no   no   
41185   56      retired  married    university.degree       no     yes   no   
41186   44   technician  married  professional.course       no      no   no   
41187   74      retired  married  professional.course       no     yes   no   

         contact month day_of_week  campaign  pdays  previous     poutcome  \
0      telephone   may         mon         1    999         0  nonexistent   
1      telephone   may         mon         1    999         0  nonexistent   
2      telephone   may         mon         1    999         0  nonexistent   
3      telephone   may         mon         1    999         0  nonexistent   
4      telephone   may         mon         1    999         0  nonexistent   
...          ...   ...         ...       ...    ...       ...          ...   
41183   cellular   nov         fri         1    999         0  nonexistent   
41184   cellular   nov         fri         1    999         0  nonexistent   
41185   cellular   nov         fri         2    999         0  nonexistent   
41186   cellular   nov         fri         1    999         0  nonexistent   
41187   cellular   nov         fri         3    999         1      failure   

       emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  nr.employed  
0               1.1          93.994          -36.4      4.857       5191.0  
1               1.1          93.994          -36.4      4.857       5191.0  
2               1.1          93.994          -36.4      4.857       5191.0  
3               1.1          93.994          -36.4      4.857       5191.0  
4               1.1          93.994          -36.4      4.857       5191.0  
...             ...             ...            ...        ...          ...  
41183          -1.1          94.767          -50.8      1.028       4963.6  
41184          -1.1          94.767          -50.8      1.028       4963.6  
41185          -1.1          94.767          -50.8      1.028       4963.6  
41186          -1.1          94.767          -50.8      1.028       4963.6  
41187          -1.1          94.767          -50.8      1.028       4963.6  

[41188 rows x 19 columns]

In [41]:
#df['job'].unique()

In [42]:
#df['marital'].unique()

In [43]:
#df['education'].unique()

In [44]:
#df['housing'].unique()

In [45]:
#df['loan'].unique()

In [46]:
#df['contact'].unique()

In [47]:
#df['month'].unique()

In [48]:
#df['day_of_week'].unique()

In [49]:
#df['poutcome'].unique()

In [50]:
# Encoding all the predictor variables to convert the categorical values to numerical values.
A = pd.get_dummies(x,drop_first=True)
print("Total number of predictors after encoding = ", len(A.columns))
# Printing the list of columns after encoding to understand the encoding process
A.columns


Total number of predictors after encoding =  52


Index(['age', 'campaign', 'pdays', 'previous', 'emp.var.rate',
       'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed',
       'job_blue-collar', 'job_entrepreneur', 'job_housemaid',
       'job_management', 'job_retired', 'job_self-employed', 'job_services',
       'job_student', 'job_technician', 'job_unemployed', 'job_unknown',
       'marital_married', 'marital_single', 'marital_unknown',
       'education_basic.6y', 'education_basic.9y', 'education_high.school',
       'education_illiterate', 'education_professional.course',
       'education_university.degree', 'education_unknown', 'default_unknown',
       'default_yes', 'housing_unknown', 'housing_yes', 'loan_unknown',
       'loan_yes', 'contact_telephone', 'month_aug', 'month_dec', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'day_of_week_mon', 'day_of_week_thu', 'day_of_week_tue',
       'day_of_week_wed', 'poutcome_nonexistent', 'poutcome_success'],
  

In [51]:
from sklearn.model_selection import train_test_split


In [52]:
x_train,x_test,y_train,y_test = train_test_split(A, y,test_size=0.8,random_state=2) 

In [55]:
#x_train

In [60]:
#y_train

# random state

In [61]:
from sklearn.tree import DecisionTreeClassifier
# Creating an object of the DecisionTreeClassifier model
dtc = DecisionTreeClassifier(random_state = 1)

In [62]:
dtc.fit(x_train,y_train)

DecisionTreeClassifier(random_state=1)

In [63]:
y_pred=dtc.predict(x_test)
y_pred

array(['no', 'no', 'yes', ..., 'no', 'no', 'no'], dtype=object)

In [64]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[26297,  2927],
       [ 2414,  1313]], dtype=int64)

In [66]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8379108373038755

In [68]:
from sklearn.metrics import recall_score
recall_score(y_test,y_pred,average='micro')

0.8379108373038755

In [69]:
from sklearn.metrics import precision_score
precision_score(y_test,y_pred,average='micro')

0.8379108373038755

# critreion

In [70]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion='entropy')

In [71]:
dtc.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [72]:
y_pred=dtc.predict(x_test)
y_pred

array(['no', 'no', 'yes', ..., 'yes', 'no', 'no'], dtype=object)

In [73]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[26321,  2903],
       [ 2478,  1249]], dtype=int64)

In [74]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8366969135989804

In [75]:
from sklearn.metrics import recall_score
recall_score(y_test,y_pred,average='micro')

0.8366969135989804

In [76]:
from sklearn.metrics import precision_score
precision_score(y_test,y_pred,average='micro')

0.8366969135989804

# splitter

In [77]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(splitter='random')

In [78]:
dtc.fit(x_train,y_train)

DecisionTreeClassifier(splitter='random')

In [79]:
y_pred=dtc.predict(x_test)
y_pred

array(['yes', 'no', 'no', ..., 'no', 'no', 'no'], dtype=object)

In [80]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[26368,  2856],
       [ 2536,  1191]], dtype=int64)

In [81]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8363630845801341

In [82]:
from sklearn.metrics import recall_score
recall_score(y_test,y_pred,average='micro')

0.8363630845801341

In [83]:
from sklearn.metrics import precision_score
precision_score(y_test,y_pred,average='micro')

0.8363630845801341